### PR TITLE
dont use SSL on development

### PR DESCRIPTION
**Pull request by Morantron**
Added `nginx.use_ssl` config var. It's used to import the letsencrypt task and in the nginx template ( to listen to the correct port ).

### CODE REVIEW

**Review by andresgutgon — DISMISSED** [review]

**Review by enricostano — CHANGES_REQUESTED** [review]
I wouldn't install nginx at all in development, same as certbot

**Review by sauloperez — DISMISSED** [review]

**Comment by andresgutgon** [comment]
Democracy wins 💪 
image

**Comment by sauloperez** [comment]
> I wouldn't install nginx at all in development, same as certbot

I would do it in a separate PR @andresgutgon :trollface:

**Review by danypr92 — APPROVED** [review]

**Comment by enricostano** [comment]
No entiendo nada :joy: 

EDIT: we said in coopdevs telegram that we don't need nginx in development, right? (same as letsencrypt)

**Comment by andresgutgon** [comment]
> we said in coopdevs telegram that we don't need nginx in development, right?

Can you paste an image were the people agreed on that? 😅 I just remember you ;)

**Comment by enricostano** [comment]
That's what we're doing in all the other coopdevs projects, and as we said in that chat is that we don't need nginx in development. To keep it simple.

Really, I just want to use the same (simple) strategy in all the projects that are similar... Keep it simple and consistent :pray:

**Comment by enricostano** [comment]
@sauloperez @danypr92 can you please reconsider your vote?

**Comment by Morantron** [comment]
I think nginx in development is useful when you have other public facing services. This way you avoid differences between production/staging/dev. Instead of lots of env vars with host+port `http://localhost:8001`, you have the same proxy pass in all environments.

If we don't have this kind of stuff in TO we can remove it, I can do it in another PR ( without this changes provision is broken :boom: )

**Comment by sauloperez** [comment]
> If we don't have this kind of stuff in TO we can remove it 

that's exactly what happens in TO. And we're trying to simplify it even further by removing unnecessary stuff.

**Comment by Morantron** [comment]
okiii, merging this to unbreak devenv, stay tuned for next PR :dancer:

**Pull request merged**
