### PR TITLE
Split secrets in vars

### PR DESCRIPTION
**Pull request by mperezv**
I splitted the secrets in staging into encrypted vars.

### CODE REVIEW

**Review by sauloperez — APPROVED** [review]

**Comment by sauloperez** [comment]
Now that there is no need for a separate secrets.yml file we can encrypt we can merge these variables into the existing config.yml. That's what we've been doing with @danypr92 .

**Review by sauloperez — APPROVED** [review]
:ok_hand: I can confirm we carried over all vars this time

**Review by danypr92 — APPROVED** [review]
Great @mperezv!

Now we can create an issue to split this file files by theme (`db.yml`, `sys_admins.yml`, `backups.yml`, ...) as in other projects like [trytond-provision](https://github.com/coopdevs/trytond_provision/tree/master/inventory/host_vars/stagingtryton.coopdevs.org).
What do you think @sauloperez?

**Comment by sauloperez** [comment]
IMO this config is not yet large enough to need multiple files. Som Connexió's infrastructure is more complex and that's why splitting makes it more clear but here, I doubt we'll improve anything.

**Review by enricostano — APPROVED** [review]

**Comment by mperezv** [comment]
Fix #146

**Pull request merged**
