### PR TITLE
Install ElasticSearch 2.4.6

### PR DESCRIPTION
**Pull request by sauloperez**
This then replaces the systemd unit template with TO's production unit.

### CODE REVIEW

**Comment by sauloperez** [comment]
@danypr92 suggests something similar to what we did with the PostgreSQL role not long ago: build a role on top of this one and then override their systemd unit with ours. Less code to maintain :ok_hand:

**Comment by sauloperez** [comment]
Tested in front of @sseerrggii with a `develop` deployment and search is working :tada:

**Comment by sauloperez** [comment]
The issue I'm having is with Travis is

```
TASK [elastic.elasticsearch : Wait for elasticsearch to startup] ***************
task path: /home/travis/build/coopdevs/timeoverflow-provisioning/vendor/elastic.elasticsearch/tasks/main.yml:52
34m<travis_ci> ESTABLISH LOCAL CONNECTION FOR USER: travis
<travis_ci> EXEC /bin/sh -c 'echo ~travis && sleep 0'
<travis_ci> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/travis/.ansible/tmp/ansible-tmp-1571225822.2888036-271604058905941 `" && echo ansible-tmp-1571225822.2888036-271604058905941="` echo /home/travis/.ansible/tmp/ansible-tmp-1571225822.2888036-271604058905941 `" ) && sleep 0'
Using module file /home/travis/virtualenv/python3.7.4/lib/python3.7/site-packages/ansible/modules/utilities/logic/wait_for.py
<travis_ci> PUT /home/travis/.ansible/tmp/ansible-local-68017qws7hh1/tmpelejxb_1 TO /home/travis/.ansible/tmp/ansible-tmp-1571225822.2888036-271604058905941/AnsiballZ_wait_for.py
<travis_ci> EXEC /bin/sh -c 'chmod u+x /home/travis/.ansible/tmp/ansible-tmp-1571225822.2888036-271604058905941/ /home/travis/.ansible/tmp/ansible-tmp-1571225822.2888036-271604058905941/AnsiballZ_wait_for.py && sleep 0'
<travis_ci> EXEC /bin/sh -c 'sudo -H -S -n  -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-zsivfpbdxguduyveixjvnjafwrbbxrak ; /usr/bin/python3 /home/travis/.ansible/tmp/ansible-tmp-1571225822.2888036-271604058905941/AnsiballZ_wait_for.py'"'"' && sleep 0'
<travis_ci> EXEC /bin/sh -c 'rm -f -r /home/travis/.ansible/tmp/ansible-tmp-1571225822.2888036-271604058905941/ > /dev/null 2>&1 && sleep 0'
fatal: [travis_ci]: FAILED! => {
    "changed": false,
    "elapsed": 300,
    "invocation": {
        "module_args": {
            "active_connection_states": [
                "ESTABLISHED",
                "FIN_WAIT1",
                "FIN_WAIT2",
                "SYN_RECV",
                "SYN_SENT",
                "TIME_WAIT"
            ],
            "connect_timeout": 1,
            "delay": 5,
            "exclude_hosts": null,
            "host": "localhost",
            "msg": null,
            "path": null,
            "port": 9200,
            "search_regex": null,
            "sleep": 1,
            "state": "started",
            "timeout": 300
        }
    },
    "msg": "Timeout when waiting for localhost:9200"
}
```

**Review by enricostano — APPROVED** [review]

**Comment by sauloperez** [comment]
I don't understand. The CI executions succeeds but the build exits with a 1 :thinking: 

```
PLAY RECAP *********************************************************************
ci_server                  : ok=102  changed=4    unreachable=0    failed=0    skipped=132  rescued=0    ignored=0   
The command "ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook playbooks/provision.yml --limit=ci_server" exited with 0.
Done. Your build exited with 1.
```

**Comment by sauloperez** [comment]
This must be it. We run the linter before anything else

```
$ ansible-lint playbooks/*.yml
206 Variables should have spaces before and after: {{ var_name }}
/home/travis/build/coopdevs/timeoverflow-provisioning/roles/elasticsearch/tasks/main.yml:13
  template: src=elasticsearch.j2 dest={{instance_sysd_script}} mode=0644 force=yes
The command "ansible-lint playbooks/*.yml" exited with 2.
```

**Pull request merged**
