### PR TITLE
remove chromedriver

### PR DESCRIPTION
**Pull request by sseerrggii**
As [reported by Jordi in community](https://community.coopdevs.org/t/error-a-lintentar-instalar-timeoverflow-en-local/935) you can't [Build development environment](https://github.com/coopdevs/timeoverflow/wiki/Build-development-environment-with-LXC-for-GNU-Linux) on

`ansible-playbook playbooks/provision.yml --limit=dev
`
return error:

```
TASK [common : Symlink chromedriver globally] **********************************
fatal: [local.timeoverflow.org]: FAILED! => {"changed": false, "gid": 0, "group": "root", "mode": "0755", "msg": "refusing to convert from file to symlink for /usr/bin/chromedriver", "owner": "root", "path": "/usr/bin/chromedriver", "size": 12375944, "state": "file", "uid": 0}
```

If I remove chrome driver from [roles/common/tasks/install_packages.yml](https://github.com/coopdevs/timeoverflow-provisioning/compare/fix/remove-chromedriver?expand=1#diff-fe93ab603f374e45926efd8a80d64a84) and everything works fine. 

I don't know what chromedriver do, maybe this problem is related with https://github.com/coopdevs/timeoverflow/commit/271a5be3b93a3fa8970e8d9b6572c1c8a1a56d6b

### CODE REVIEW

**Comment by enricostano** [comment]
LOL, nice try @sseerrggii :joy: 

But we need chromedriver to execute feature specs locally. Can you please create an issue reporting this? Thanks!

**Comment by sseerrggii** [comment]
Hehe :smiling_imp: 

Issue 👉 https://github.com/coopdevs/timeoverflow-provisioning/issues/67

**Comment by enricostano** [comment]
@sseerrggii todo tuyo :sweat_smile:

**Comment by sseerrggii** [comment]
Incredible but true, I was right :scream_cat: 

https://github.com/coopdevs/timeoverflow-provisioning/issues/67#issuecomment-493057691

I will test it

**Comment by sseerrggii** [comment]
Testing following this [guide](https://github.com/coopdevs/timeoverflow/wiki/Build-development-environment-with-LXC-for-GNU-Linux) 

I have this error on: 

`timeoverflow@timeoverflow:/var/www/timeoverflow$ bundle exec rake db:setup`


`Redis::CannotConnectError: Error connecting to Redis on 127.0.0.1:6379 (Errno::ECONNREFUSED)
`

---
Seems that redis-server didn't start, if I started manually

`timeoverflow@timeoverflow:/var/www/timeoverflow$ redis-server`

I can continue and run the app && bundle exec rspec spec/features

**Comment by enricostano** [comment]
> I can continue and run the app && bundle exec rspec spec/features

And? Does it work?

**Comment by sseerrggii** [comment]
Yes!! app && bundle exec rspec spec/features works

**Review by enricostano — APPROVED** [review]

**Pull request merged**
